SET STATEMENT_TIMEOUT = 0;
SET LOCK_TIMEOUT = 0;
SET IDLE_IN_TRANSACTION_SESSION_TIMEOUT = 0;
SET CLIENT_ENCODING = 'UTF8';
SET STANDARD_CONFORMING_STRINGS = ON;
SELECT PG_CATALOG.SET_CONFIG('SEARCH_PATH', '', FALSE);
SET CHECK_FUNCTION_BODIES = FALSE;
SET XMLOPTION = CONTENT;
SET CLIENT_MIN_MESSAGES = WARNING;
SET ROW_SECURITY = OFF;

SET DEFAULT_TABLESPACE = '';

CREATE TABLE PUBLIC.USERS (
  USER_ID UUID NOT NULL PRIMARY KEY,
  EMAIL VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.ROLES (
  ROLE_ID UUID NOT NULL PRIMARY KEY,
  ROLE_NAME VARCHAR NOT NULL
);

CREATE TABLE PUBLIC.ROLES_USERS (
  ROLE_ID UUID NOT NULL,
  USER_ID UUID NOT NULL
);

CREATE TABLE PUBLIC.ARTICLES (
  ARTICLE_ID UUID NOT NULL PRIMARY KEY,
  USER_ID UUID NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR NOT NULL,
  CONTENT VARCHAR NOT NULL,
  PUBLISHED_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT (NOW())
);

ALTER TABLE PUBLIC.ROLES_USERS ADD FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.ROLES(ROLE_ID);

ALTER TABLE PUBLIC.ROLES_USERS ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);

ALTER TABLE PUBLIC.ARTICLES ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID);

ALTER TABLE PUBLIC.ROLES_USERS ADD CONSTRAINT pk__user_role UNIQUE (ROLE_ID, USER_ID);

INSERT INTO PUBLIC.ROLES(ROLE_ID, ROLE_NAME) VALUES ('2c511b0c-fc47-4801-99d5-525efc89708e', 'USER'), ('e63bf7e9-86d4-46a8-9ab2-4b37a0d7dca5', 'ADMIN');